modera_languages:
    - { locale: en }
    - { locale: ru }
    - { locale: et }

modera_file_uploader:
    is_enabled: true
    url: /backend/uploader-gateway

modera_server_crud:
    exception_handler: modera_server_crud.exception_handling.bypass_handler

modera_mjr_integration:
    runtime_path: "/modera/mjr"
    viewport_class: "MF.theme.authenticationaware.Viewport"
    main_config_provider: "modera_dynamically_configurable_mjr.mjr.main_config"
    # If you don't have a local copy of ExtJs 4.2 at hand you can use a CDN instead
    # by uncommenting the following line:
    # extjs_path: https://cdnjs.cloudflare.com/ajax/libs/extjs/4.2.1/

modera_mjr_theme_integration:
    theme_path: "/modera/theme"

modera_mjr_security_integration:
    login_url: _security_check
    logout_url: _security_logout
    is_authenticated_url: modera_mjr_security_integration.index.is_authenticated
