root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path:   %modera_mjr_integration.route_prefix%
        permanent: true

_modera_routing:
    resource: "@ModeraRoutingBundle/Resources/config/routing.yml"